output window details when found. Make sure only 1 window is found

diff --git a/bin/webrf b/bin/webrf
--- a/bin/webrf
+++ b/bin/webrf
@@ -14,7 +14,7 @@ WR_FILE=~/.webrf
 function usage() {
 	echo "$NAME: web browser refresh automation helper. https://github.com/rynop/webrf"
 	echo "USAGE: "
-	echo "  $NAME setup-by-search \"case sensitive window name - typically html <title> to search for\""
+	echo "  $NAME setup-by-search \"case sensitive window name (only need part of name)\""
 	echo " -OR-"
 	echo "  $NAME setup-by-id <browser window ID>"
 	echo ""
@@ -29,20 +29,35 @@ function usage() {
 }
 
 function xdotool_installed() {
-	which xdotool
+	which xdotool &> /dev/null 
 	if [ $? -ne "0" ]; then
 		echo "!!ERROR: xdotool must be installed and on your path"
 		exit 1
 	fi
 }
 
+function showWindowDetails() {
+	WID="$1"
+	WINNAME=`xdotool getwindowname $WID`
+	
+	echo "Window found. Ready for refreshing! Details:"
+	echo "  * Window Name: $WINNAME"
+	echo "  * Window ID: $WID" 
+}
+
 function setup_by_search() {
 	echo "" > $WR_FILE
-
-    xdotool search "$1" | head -1 > $WR_FILE
-
-	if [ -s "$WR_FILE" ]; then
-		echo "Window found. Ready for refreshing!"		
+	
+    NUMWINS=`xdotool search "$1" 2>/dev/null | wc -l`
+    if [ $NUMWINS -gt "1" ]; then
+    	echo "!!ERROR: more than one window found. Do a more specific search"
+    	exit 1
+    fi
+    
+    WID=`xdotool search "$1" 2>/dev/null | head -1`    
+    echo $WID > $WR_FILE
+	if [ "$NUMWINS" -eq "1" ]; then
+		showWindowDetails $WID
 	else
 		echo "!!ERROR: window not found. See usage"
 		exit 1
@@ -50,10 +65,11 @@ function setup_by_search() {
 }
 
 function setup_by_id() {
-	echo "$1" > $WR_FILE
+	WID="$1"
+	echo "$WID" > $WR_FILE
 
 	if [ -s "$WR_FILE" ]; then
-		echo "Window found. Ready for refreshing!"		
+		showWindowDetails $WID		
 	else
 		echo "!!ERROR: window not found. See usage"
 		exit 1
